### ISSUE TITLE
I have a question...!

### ISSUE THREAD

**Issue by PedroD** [wurstmeister/storm-docker#21]
In this file: https://github.com/wurstmeister/storm-docker/blob/master/storm/start-supervisor.sh

you use these two ENVs: `$ZK_PORT_2181_TCP_ADDR` and `$NIMBUS_PORT_6627_TCP_ADDR`

Where are they coming from? I never defined them and this just works.

**Comment by ColadaFF** [comment]
Hi there,

Take a look at this: https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/
on the "Environment variables" section.

**Comment by ColadaFF** [comment]
Hi there,

Take a look at [Docker Links Documentation](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/), on the "Environment variables" section.

**Comment by wurstmeister** [comment]
Thanks @ColadaFF for providing the answer.

**Comment by jadowdl** [comment]
With more recent versions of docker, e.g. Docker for Mac 17.06.0-ce, version 1 of the docker-compose.yaml is not supported, and these variables are no longer being populated (e.g. https://github.com/docker/compose/issues/3268), which causes everything to break.  Hopefully @wurstmeister can get around to updating the project.  In the meantime, a work around (for anybody else who runs into this) is to inject the ENV variables yourself and have them resolve to hostnames (that are populated when using `links` instead of the ENV variables, in version 2 and 3), e.g.

```
version: '3'  # Docker Compose file version 3.x

services:
  ## ZOOKEEPER
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  ## STORM
  storm-nimbus:
    image: wurstmeister/storm-nimbus
    ports:
      - "49773:3773"
      - "49772:3772"
      - "49627:6627"
      - "22"
    links:
      - zookeeper:zk
    environment:
      ZK_PORT_2181_TCP_ADDR: "zk"

  storm-supervisor:
    image: wurstmeister/storm-supervisor
    ports:
      - "8000"
      - "22"
    links:
      - storm-nimbus:nimbus
      - zookeeper:zk
    environment:
      ZK_PORT_2181_TCP_ADDR: "zk"
      NIMBUS_PORT_6627_TCP_ADDR: "nimbus"

  storm-ui:
    image: wurstmeister/storm-ui
    ports:
      - "49080:8080"
      - "22"
    links:
      - storm-nimbus:nimbus
      - zookeeper:zk
    environment:
      ZK_PORT_2181_TCP_ADDR: "zk"
      NIMBUS_PORT_6627_TCP_ADDR: "nimbus"
```
